apiVersion: v1
kind: Pod
metadata:
  name: rbd-test-pod
  namespace: default
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["echo 'RBD working!' > /mnt/rbd/test.txt && sleep 3600"]
      volumeMounts:
        - mountPath: /mnt/rbd
          name: rbd-vol
  volumes:
    - name: rbd-vol
      persistentVolumeClaim:
        claimName: rbd-pvc
