apiVersion: v1
kind: Pod
metadata:
  name: cephfs-test-pod
spec:
  containers:
    - name: test
      image: docker.io/library/busybox:latest
      command: ["sh", "-c"]
      args:
        - |
          echo "CephFS is working!" > /mnt/cephfs/test.txt;
          cat /mnt/cephfs/test.txt;
          sleep 3600;
      volumeMounts:
        - name: cephfs-vol
          mountPath: /mnt/cephfs
  volumes:
    - name: cephfs-vol
      persistentVolumeClaim:
        claimName: cephfs-test-pvc
